# base image
FROM cypress/browsers:node12.8.1-chrome78-ff70

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install cypress
COPY package.json /usr/src/app/package.json
RUN npm install

# copy cypress files and folders
COPY cypress /usr/src/app/cypress
COPY cypress.json /usr/src/app/cypress.json

# confirm the cypress install
RUN ./node_modules/.bin/cypress --version
